version: '3'
services:
  backend:
    environment:
      EXCLUDE_PORTS: 443
      VIRTUAL_HOST: ${PROJECT_DOMAIN}
      AWS_REGION: ${AWS_REGION}
    volumes:
      - ./src:/app
      - $HOME/.aws:/root/.aws
    labels:
      - lb.hook=true
